runtime: python39  # Use the appropriate runtime for your application
entrypoint: uvicorn app.main:app --host=0.0.0.0 --port=$PORT  # Adjust entrypoint based on your application structure

# Optional: Configure your app
env: standard
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# Optional: Add any additional settings like handlers
handlers:
  - url: /.*
    script: auto
