version: 2.1
orbs:
  python: circleci/python@2


executors:
  python-executor:
    docker:
      - image: cimg/python:3.8  # Define the Docker image for the executor
    working_directory: ~/project  # Set the working directory for the job

jobs:
  build:
    # Install dependencies and run tests
    docker:
      - image: cimg/python:3.8-node
    executor: python-executor
    steps:
      - checkout  # Check out your code
      - python/install-packages  # Install dependencies using your package manager (pip/poetry)
      - run:
          name: Set Up Python
          command: python -m venv venv && . venv/bin/activate
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            pytest --junitxml=junit.xml --cov=app --cov-report=xml
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: coverage.xml
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: deploy to app engine
          command: |
            echo ${GCLOUD_KEY} > /tmp/sa_key.json
            gcloud auth activate-service-account --key-file=/tmp/sa_key.json
            rm /tmp/sa_key.json
            gcloud config set project football-project-c5ca5
            gcloud config set compute/region us-central
            gcloud app deploy app.yaml

workflows:
  build-and-test:
    jobs:
      - build
      - deploy:
          requires:
            - build
