version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    # Install dependencies and run tests
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout  # Check out your code
      - python/install-packages  # Install dependencies using your package manager (pip/poetry)
      - run:
          name: Run Unit Tests
          command: pytest --junitxml=junit.xml --cov=app/tests --cov-report=xml  # Add coverage report
      - store_test_results:
          path: junit.xml  # Store test results for CircleCI's UI
      - store_artifacts:
          path: coverage.xml  # Store coverage report
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      # Placeholder deploy job
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-python
    # - deploy:
    #     requires:
    #       - test-python
