version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    # Install dependencies and run tests
    docker:
      - image: cimg/python:3.8-node
    executor: python-executor
    steps:
      - checkout  # Check out your code
      - python/install-packages  # Install dependencies using your package manager (pip/poetry)
      - run:
          name: Set Up Python
          command: python -m venv venv && . venv/bin/activate
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            pytest --junitxml=junit.xml --cov=app --cov-report=xml
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: coverage.xml
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      # Placeholder deploy job
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-python
    # - deploy:
    #     requires:
    #       - test-python
